require 'hoe'
require './lib/unisat/version.rb'

Hoe.spec 'unisat' do

  self.version =  Unisat::VERSION

  self.summary = "unisat - lite helpers for full-text search in bitcoin ordinal inscriptions powered by unisat.io"
  self.description = summary

  self.urls    = { home: 'https://github.com/ordbase/ordbase' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
    ['puppeteer-ruby'],
    ['nokogiri'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
